### ISSUE TITLE
Link to java and php challenge must point to a landing page that redirects to the backend developer position on breezy

### ISSUE THREAD

**Issue by ghost** [Multidialogo/multidialogo.github.io#4]
The page must show a message.

Sorry, we do not have active "language name" challenges available, but you still can apply to our backend developer position:

-> redirect with meta tag to:

https://multidialogo.breezy.hr/p/ad020106a18a01-backend-web-developer

**Comment by emidiocruciani** [comment]
Add breezy redirect to devops, frontend and designer pages
